AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GitHub OIDC Deployment Role

Parameters:
  GitHubOrg:
    Description: Name of GitHub organization/user (case sensitive).
    Type: String
  RepositoryName:
    Description: Name of GitHub repository (case sensitive).
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Type: String
  OIDCAudience:
    Description: Audience supplied to configure-aws-credentials.
    Default: "sts.amazonaws.com"
    Type: String
  RoleName:
    Description: Name for the IAM Role.
    Type: String

Conditions:
  CreateOIDCProvider: !Equals
    - !Ref OIDCProviderArn
    - ""

Metadata:
  AWS::ServerlessRepo::Application:
    Name: core-aws-github-role
    Description: Create a deployment role for a GitHub repo
    Author: tiki
    SpdxLicenseId: MIT
    LicenseUrl: ../../LICENSE
    ReadmeUrl: ../../README.md
    Labels: ['github']
    HomePageUrl: https://github.com/tiki/core-aws-github-role
    SemanticVersion: 0.1
    SourceCodeUrl: https://github.com/tiki/core-aws-github-role

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GithubOidc
                - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref OIDCAudience
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${GitHubOrg}/${RepositoryName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - ffffffffffffffffffffffffffffffffffffffff

Outputs:
  Arn:
    Value: !GetAtt Role.Arn
